version: "3.8"
services:
  api_a:
    build: .
    command: uvicorn api_A.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  
  api_b:
    build: .
    command: uvicorn api_B.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
